import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";

const inter = localFont({
  src: "../public/InterVariable.woff2",
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={`${inter.variable} font-sans p-6 max-w-5xl mx-auto min-[512px]:px-16 lg:px-4`}
        >
          {children}
        </body>
      </html>
    </ViewTransitions>
  );
}
