import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import Sidebar from "./sidebar";
import { Suspense } from "react";
import { VercelToolbar } from "@vercel/toolbar/next";

const wantedSans = localFont({
  src: "../fonts/WantedSansVariable.woff2",
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className=" dark ">
      <body
        className={cn(
          wantedSans.variable,
          "font-sans flex bg-gray-1 text-gray-12"
        )}
      >
        {/* <Sidebar /> */}
        <div className="w-full  overflow-x-hidden">{children}</div>
        <Suspense>
          <VercelToolbar />
        </Suspense>
      </body>
    </html>
  );
}
